sudo: false
language: scala
services:
- docker
scala: 2.12.12
jdk: openjdk8
before_install:
  - docker-compose -f docker-compose.test.yml rm -f
  - docker-compose -f docker-compose.test.yml up -d
script: sbt -J-XX:ReservedCodeCacheSize=128m ++$TRAVIS_SCALA_VERSION  -Dsbt.color=always -Dsbt.supershell=false test
#
#stages:
#  # runs on develop, master commits and PRs
#  - name: test_compile
#    if: NOT tag =~ ^v
#  - name: publish
#    if: tag =~ ^v
#
#jobs:
#  include:
#    - stage: test_compile
#      name: "Run unit test"
#      before_install: docker-compose -f docker-compose.test.yml up -d
#      script:
#        - sbt -J-XX:ReservedCodeCacheSize=128m ++$TRAVIS_SCALA_VERSION  -Dsbt.color=always -Dsbt.supershell=false test
#    - stage: publish
#      name: "Pusblish to bintray"
#      script:
#        - sbt -J-Xmx2G -J-Xss20M -J-XX:ReservedCodeCacheSize=128m ++$TRAVIS_SCALA_VERSION  -Dsbt.color=always -Dsbt.supershell=false "publish"

before_cache:
- find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
- find $HOME/.sbt  -name "*.lock"               -print -delete
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot"
  - "$HOME/.sbt"